package es.uc3m.baldo.opinais.ir.readers.factories;

import es.uc3m.baldo.opinais.ir.items.TextItem;

/**
 * TextItemFactory.
 * <p>All text items factories must implement this interface.</p>
 * 
 * @param <T> particular type of text item to be generated by the factory.
 * @param <E> type of input inserted into the factory to generate the new object.
 * 
 * @author Alejandro Baldominos
 */
public interface TextItemFactory<T extends TextItem, E> extends Factory<T, E> {
	
	/**
	 * <p>Generates an instance of a text item given a certain object.</p>
	 *
	 * @param text the input text, which will serve to made the text item.
	 * @return a text item.
	 */
	@Override
	public T make (E text);

}
